export const newsData = [
  {
    id: 1,
    title: 'Новые танки',
    body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque ab perferendis numquam deleniti necessitatibus, id nisi eius enim ipsam dignissimos ratione soluta, adipisci sit dolorum, voluptatibus incidunt. Quas, maxime sequi?',
    link: '/news',
    date: '18.03.2024',
    linkName: 'Новости',
    discord: 'https://discord.gg/world-of-tanks',
  },
  {
    id: 2,
    title: 'Привет из мира танков',
    body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque ab perferendis numquam deleniti necessitatibus, id nisi eius enim ipsam dignissimos ratione soluta, adipisci sit dolorum, voluptatibus incidunt. Quas, maxime sequi?',
    link: '/news',
    date: '17.03.2024',
    linkName: 'Новости',
    discord: 'https://discord.gg/world-of-tanks',
  },
  {
    id: 3,
    title: 'Обновление 3.32',
    body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque ab perferendis numquam deleniti necessitatibus, id nisi eius enim ipsam dignissimos ratione soluta, adipisci sit dolorum, voluptatibus incidunt. Quas, maxime sequi?',
    link: '/news',
    date: '16.03.2024',
    linkName: 'Новости',
    discord: 'https://discord.gg/world-of-tanks',
  },
  {
    id: 4,
    title: 'Весенняя распродажа',
    body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque ab perferendis numquam deleniti necessitatibus, id nisi eius enim ipsam dignissimos ratione soluta, adipisci sit dolorum, voluptatibus incidunt. Quas, maxime sequi?',
    link: '/news',
    date: '15.03.2024',
    linkName: 'Новости',
    discord: 'https://discord.gg/world-of-tanks',
  },
  {
    id: 5,
    title: 'Премиум-танки',
    body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque ab perferendis numquam deleniti necessitatibus, id nisi eius enim ipsam dignissimos ratione soluta, adipisci sit dolorum, voluptatibus incidunt. Quas, maxime sequi?',
    link: '/news',
    date: '14.03.2024',
    linkName: 'Новости',
    discord: 'https://discord.gg/world-of-tanks',
  },
  {
    id: 6,
    title: 'Редкая награда',
    body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque ab perferendis numquam deleniti necessitatibus, id nisi eius enim ipsam dignissimos ratione soluta, adipisci sit dolorum, voluptatibus incidunt. Quas, maxime sequi?',
    link: '/news',
    date: '13.03.2024',
    linkName: 'Новости',
    discord: 'https://discord.gg/world-of-tanks',
  },
];
